name: Hexo Blog Delopy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # @see https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master

    # @see https://github.com/actions/setup-node
    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: "14"

    - name: Setup Hexo Dependencies
      run: |
        npm install hexo-cli -g

    - name: Setup Git Infomation
      run: |
        git config --global user.name 'xyz8848'
        git config --global user.email 'xyz8848git@outlook.com'

    - name: Deploy Hexo
      run: |
        hexo generate
        hexo deploy

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        # 部署到 gh-pages 分支
        target_branch: gh-pages
        # 部署目录为 Hexo 的默认输出目录
        build_dir: public
        # 域名(CNAME)
        fqdn: blog.xyz8848.com
        # 强制提交
        keep_history: true
      env:
        # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
